### ISSUE TITLE
Add PHP 8.1

### ISSUE THREAD

**Issue by katieescoto** [thinkshout/ts_environment#52] opened 2022-07-01 22:36 UTC
Adding PHP 8.1 to TS environment.

**Comment by mariacha** [comment] 2023-09-18 15:52
This is done, but the issue is still open, so closing! https://github.com/thinkshout/ts_environment/blob/9bf3ad672c5fba8d4cc6977f3aeef443d5ca5847/scripts/php.sh#L14

**Closed as completed by mariacha** 2023-09-18 15:52 UTC
