### ISSUE TITLE
Oct. run

### ISSUE THREAD

**Issue by mariacha** [thinkshout/ts_environment#21] opened 2018-10-03 01:41 UTC
Some issues I noticed while running this on my clean machine:

- I hadn't logged into the App Store yet, because I wanted to get 1password (my pw is long), so I got this:

```
Error: Unable to install Keynote app. mas not signed in to Mac App Store.
```

when attempting to download keynote. I already had keynote, so not a big deal, but maybe we should add it to the note at the beginning? Something like "Recommended: Be logged into the Mac App Store"

- P4merge error. Not sure what this is for?

```
Error: Cask 'p4merge' is unavailable: No Cask with this name exists.
Installing p4merge has failed!
```

**Comment by wxactly** [comment] 2019-10-07 17:15
Duplicate of #28

**Closed as completed by wxactly** 2019-10-07 17:15 UTC
